export enum AreaGeograficaTipoMSG {
  FIND_ALL = 'FIND_AREA_GEOGRAFICA_TIPOS',
  FIND_ONE = 'FIND_AREA_GEOGRAFICA_TIPO',
  CREATE_ONE = 'CREATE_AREA_GEOGRAFICA_TIPO',
  UPDATE_ONE = 'UPDATE_AREA_GEOGRAFICA_TIPO',
  DELETE_ONE = 'DELETE_AREA_GEOGRAFICA_TIPO',
}
