export enum CensoTipoMSG {
  FIND_ALL = 'FIND_CENSO_TIPOS',
  FIND_ONE = 'FIND_CENSO_TIPO',
  CREATE_ONE = 'CREATE_CENSO_TIPO',
  UPDATE_ONE = 'UPDATE_CENSO_TIPO',
  DELETE_ONE = 'DELETE_CENSO_TIPO',
}
