export enum EstadoCivilTipoMSG {
  FIND_ALL = 'FIND_ESTADO_CIVIL_TIPOS',
  FIND_ONE = 'FIND_ESTADO_CIVIL_TIPO',
  CREATE_ONE = 'CREATE_ESTADO_CIVIL_TIPO',
  UPDATE_ONE = 'UPDATE_ESTADO_CIVIL_TIPO',
  DELETE_ONE = 'DELETE_ESTADO_CIVIL_TIPO',
}
