export enum GeneroTipoMSG {
  FIND_ALL = 'FIND_GENERO_TIPOS',
  FIND_ONE = 'FIND_GENERO_TIPO',
  CREATE_ONE = 'CREATE_GENERO_TIPO',
  UPDATE_ONE = 'UPDATE_GENERO_TIPO',
  DELETE_ONE = 'DELETE_GENERO_TIPO',
}
