export enum UnidadTerritorialMSG {
  FIND_ALL = 'FIND_UNIDAD_TERRITORIALS',
  FIND_ONE = 'FIND_UNIDAD_TERRITORIAL',
  CREATE_ONE = 'CREATE_UNIDAD_TERRITORIAL',
  UPDATE_ONE = 'UPDATE_UNIDAD_TERRITORIAL',
  DELETE_ONE = 'DELETE_UNIDAD_TERRITORIAL',
}
