export enum UnidadTerritorialTipoMSG {
  FIND_ALL = 'FIND_UNIDAD_TERRITORIAL_TIPOS',
  FIND_ONE = 'FIND_UNIDAD_TERRITORIAL_TIPO',
  CREATE_ONE = 'CREATE_UNIDAD_TERRITORIAL_TIPO',
  UPDATE_ONE = 'UPDATE_UNIDAD_TERRITORIAL_TIPO',
  DELETE_ONE = 'DELETE_UNIDAD_TERRITORIAL_TIPO',
}
