export enum UsuarioMSG {
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_USER',
  FIND_ONE_BY_USERNAME = 'FIND_USER_BY_USERNAME',
  CREATE_ONE = 'CREATE_USER',
  UPDATE_ONE = 'UPDATE_USER',
  DELETE_ONE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
  FIND_PROFILE = 'FIND_PROFILE',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
